#pragma once

#include <cassert>

//[Levels]
#define ALBEDO_ASSERT_LEVEL_NORMAL
#ifndef ALBEDO_ASSERT_LEVEL_NORMAL
	#define ALBEDO_ASSERT_LEVEL_DEBUG
#endif

//[Macros]
#ifdef ALBEDO_ASSERT_LEVEL_NORMAL
	#define ALBEDO_ASSERT(EXPRESSION)			assert(EXPRESSION)
	#define ALBEDO_ASSERT_DEBUG(EXPRESSION)
#elif ALBEDO_ASSERT_LEVEL_STRICT
	#define ALBEDO_ASSERT(EXPRESSION)			assert(EXPRESSION)
	#define ALBEDO_ASSERT_DEBUG(EXPRESSION)		assert(EXPRESSION)
#endif
